parameters:
  redeye_amcharts.twig_extension.class: RedEye\AmChartsBundle\Twig\AmChartsExtension

services:
  redeye_amcharts.twig.amcharts_extension:
    class: %redeye_amcharts.twig_extension.class%
    tags:
        - { name: twig.extension }
